/* ========================================================================
 * Copyright 2014 SportGroup
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 SportGroup
  
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
  
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
  
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 * ========================================================================
  
  
 Source generated by CrudMaker version 1.0.0.201411201032*/
package stamp.logic.converter;

import stamp.logic.dto.StampDTO;
import stamp.logic.entity.StampEntity;
import java.util.ArrayList;
import java.util.List;

public class StampConverter {

    public static StampDTO entity2PersistenceDTO(StampEntity entity) {
        if (entity != null) {
            StampDTO dto = new StampDTO();
            dto.setId(entity.getId());
            dto.setTema(entity.getTema());
            dto.setRating(entity.getRating());
            dto.setPopularidad(entity.getPopularidad());
            return dto;
        } else {
            return null;
        }
    }

    public static StampEntity persistenceDTO2Entity(StampDTO dto) {
        if (dto != null) {
            StampEntity entity = new StampEntity();
            entity.setId(dto.getId());

            entity.setTema(dto.getTema());

            entity.setRating(dto.getRating());

            entity.setPopularidad(dto.getPopularidad());

            return entity;
        } else {
            return null;
        }
    }

    public static List<StampDTO> entity2PersistenceDTOList(List<StampEntity> entities) {
        List<StampDTO> dtos = new ArrayList<StampDTO>();
        for (StampEntity entity : entities) {
            dtos.add(entity2PersistenceDTO(entity));
        }
        return dtos;
    }

    public static List<StampEntity> persistenceDTO2EntityList(List<StampDTO> dtos) {
        List<StampEntity> entities = new ArrayList<StampEntity>();
        for (StampDTO dto : dtos) {
            entities.add(persistenceDTO2Entity(dto));
        }
        return entities;
    }
}
